/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function FD(props) {
   const { nodes, materials } = useGLTF("models/FM.glb");
   return (
      <group {...props} dispose={null}>
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.path1002.geometry}
            material={materials["SVGMat.003"]}
            position={[-0.147, -0.144, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={4.86}
         />
         <mesh
            castShadow
            receiveShadow
            geometry={nodes.path1.geometry}
            material={materials["SVGMat.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={4.86}
         />
      </group>
   );
}

useGLTF.preload("models/FM.glb");
